// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATMPeVYLDdBqIKvll3kobMigmQvdH-hUk',
    appId: '1:184557725634:web:d3c11df990a565bf7ad85b',
    messagingSenderId: '184557725634',
    projectId: 'fir-project-7afa6',
    authDomain: 'fir-project-7afa6.firebaseapp.com',
    storageBucket: 'fir-project-7afa6.appspot.com',
    measurementId: 'G-YCL73J4518',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATPXHNidyXDeFxLGycgwCjoadB0vJimwk',
    appId: '1:184557725634:android:2a642cbf83ce06647ad85b',
    messagingSenderId: '184557725634',
    projectId: 'fir-project-7afa6',
    storageBucket: 'fir-project-7afa6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOxqPYoYHdvdg_RvqtVYN5wSuZ-e_xomQ',
    appId: '1:184557725634:ios:a3532c9e6ca646387ad85b',
    messagingSenderId: '184557725634',
    projectId: 'fir-project-7afa6',
    storageBucket: 'fir-project-7afa6.appspot.com',
    iosClientId: '184557725634-hd05f8eccjh6n2aijren135mad5uhrcb.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseBasics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOxqPYoYHdvdg_RvqtVYN5wSuZ-e_xomQ',
    appId: '1:184557725634:ios:a3532c9e6ca646387ad85b',
    messagingSenderId: '184557725634',
    projectId: 'fir-project-7afa6',
    storageBucket: 'fir-project-7afa6.appspot.com',
    iosClientId: '184557725634-hd05f8eccjh6n2aijren135mad5uhrcb.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseBasics',
  );
}
